name: Automação de Versão e Tag

on:
  push:
    branches:
      - master

jobs:
  version_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Instalar dependências
        run: npm install

      - name: Incrementar versão e atualizar app.json
        run: npm run release

      - name: Commitar alterações no app.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add app.json
            git commit -m "chore: atualiza app.json para versão $(jq -r '.version' package.json)"
            git push
          else
            echo "Nenhuma alteração no app.json para commitar."
          fi

      - name: Push das alterações e tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags