name: CI - Mobile App com Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Incrementar versão e atualizar app.json
        run: npm run release

      - name: Push das alterações e tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags

      - name: Efetuar login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Criar imagem docker
        run: |
          docker build -t projetointegradorfatec/projeto-cadastro-app:latest .
          docker tag projetointegradorfatec/projeto-cadastro-app:latest projetointegradorfatec/projeto-cadastro-app:$(jq -r '.version' package.json)

      - name: Efetuar push da imagem
        run: |
          docker push projetointegradorfatec/projeto-cadastro-app:latest
          docker push projetointegradorfatec/projeto-cadastro-app:$(jq -r '.version' package.json)